# -*- coding: utf-8 -*-
"""lenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pgSmIwLcy2BNWBIUFXZ_VL5gchRlhtb
"""

import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

rows, cols = 28, 28

x_train = x_train.reshape(x_train.shape[0], rows, cols, 1)
x_test = x_test.reshape(x_test.shape[0], rows, cols, 1)

input_shape = (rows,cols,1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255.0
x_test = x_test / 255.0

y_train = tf.keras.utils.to_categorical(y_train, 10)

def build_lenet(input_shape):

  model = tf.keras.Sequential()

  model.add(tf.keras.layers.Conv2D(filters=6, strides=(1,1), kernel_size=(5,5), activation='tanh', input_shape=input_shape))

  model.add(tf.keras.layers.AveragePooling2D(pool_size=(2,2), strides=(2,2)))

  model.add(tf.keras.layers.Conv2D(filters=6, strides=(1,1), kernel_size=(5,5), activation='tanh'))

  model.add(tf.keras.layers.AveragePooling2D(pool_size=(2,2), strides=(2,2)))

  model.add(tf.keras.layers.Dense(units=120, activation='tanh'))

  model.add(tf.keras.layers.Flatten())

  model.add(tf.keras.layers.Dense(units=84, activation='tanh'))

  model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

  return model

lenet = build_lenet(input_shape)

lenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

epochs = 10
history = lenet.fit(x_train, y_train, epochs=epochs,batch_size=128, verbose=1)

lenet.save("lenet.keras")

if len(y_test.shape) != 2 or y_test.shape[1] != 10:
  y_test = tf.keras.utils.to_categorical(y_test, 10)

loss ,acc= lenet.evaluate(x_test, y_test)
print('Accuracy : ', acc)

x_train = x_train.reshape(x_train.shape[0], 28,28)
print('Training Data', x_train.shape, y_train.shape)
x_test = x_test.reshape(x_test.shape[0], 28,28)
print('Test Data', x_test.shape, y_test.shape)

image_index = np.random.randint(0, 10000)
plt.imshow(x_test[image_index].reshape(28,28), cmap='Greys')

pred = lenet.predict(x_test[image_index].reshape(1, rows, cols, 1 ))
print(f'Prediction for image at index {image_index} : {pred.argmax()}')

